### ISSUE TITLE
Add game specific music(kind of like the wii's channels)

### ISSUE THREAD

**Issue by guiege** [EMERALD0874/SDH-AudioLoader#12]
This is kind of a shot in the dark but I think it would be really cool if you could assign a song to play whenever you click on an app. It would be like the wiis disk channels whenever you click on a game. For all actual wii games even non wii games, I think it would be a really cool addition.

**Comment by Haxorzz** [comment]
I think a (maybe) easier idea is custom music for different screens (Ex: library, settings, home, media, etc.). Then we could make music packs like wiiu or 3ds that had tracks for separate screens which is really cool in my opinion

**Comment by guiege** [comment]
Yeah im gonna try making it myself and see how it goes. So far I found a way to find the current steam appID from the protondb badges plugin.

**Comment by EMERALD0874** [comment]
This is outside the scope of this plugin. Even if such a plugin were to be made, I think you would need to start a database of jingles for each game.
