### ISSUE TITLE
Suggestion: Ability to adjust volume for sound effect and background music

### ISSUE THREAD

**Issue by lnkd61** [EMERALD0874/SDH-AudioLoader#17]
It would be nice to have the option to adjust the volume level for Audio Loader.

**Comment by EMERALD0874** [comment]
We have investigated this in the past but could not find a way to choose the volume of a sound in the functions Valve provides. It's unlikely we'll be able to fix this, but I'll leave the issue open just in case.

**Comment by cheyngoodman** [comment]
What about using [ffmpeg to alter the volume](https://trac.ffmpeg.org/wiki/AudioVolume)? A wrapper could create a new cached sound pack with the altered volume and then apply that cached sound pack.
