### ISSUE TITLE
Can't download packs

### ISSUE THREAD

**Issue by Shinmera** [EMERALD0874/SDH-AudioLoader#18]
After installing the plugin I can't seem to actually download or install packs when I go into the pack browser. The install button is grayed out and pressing it doesn't do anything. Am I missing something?

**Comment by EMERALD0874** [comment]
Have you tried restarting your Steam Deck?

**Comment by Shinmera** [comment]
I thought I had tried that, but it seems to work now after restarting again. Thanks!

**Comment by boardfish** [comment]
Also having this issue. Have experienced this when installing AudioLoader 1.1.4 and 1.4.0 on Decky v2.4.14-pre1 and v2.4.7. SteamOS Holo version 3.4.4 (20221228.1).

The install button shows as grey, then a sound effect plays and it turns white when tapped. When tapped again, the button appears disabled. Packs don't appear in the uninstall section or selector, even after rebooting, reloading the plugin, or reinstalling the plugin.

**Comment by EMERALD0874** [comment]
1. Are you on a Steam Deck?
2. Can you try reinstalling (not updating) Decky Loader? There were permissions issues added to recent builds of Decky that should be resolved.

**Comment by boardfish** [comment]
It's a little nuclear, but it appears to have worked. Thanks for your quick response!
