### ISSUE TITLE
Accidently muted steam / chromium

### ISSUE THREAD

**Issue by BlurryKnight** [EMERALD0874/SDH-AudioLoader#31]
So i went to desktop mode and my bg music started playing suddenly, so i went to the audio controller and muted chromium. Forgot to unmute it then and now steam is completley muted (UI Sounds, Music etc)
Any way to fix this? XD

**Comment by EMERALD0874** [comment]
Because this is not related to the Audio Loader, we can't help with this issue. I imagine you just need to go to the audio controller and unmute Chromium to fix your issue.
