### ISSUE TITLE
Feature Request: Pause music on game view/Cross-compatibility with the gameview plugin

### ISSUE THREAD

**Issue by WMan22** [EMERALD0874/SDH-AudioLoader#43]
Source code: https://github.com/lcd1232/gameview-music-deck

Music library: https://github.com/lcd1232/gameview-music-data

I'd like it if AudioLoader had an option to pause music when looking at a game's page, so that Game View's music can start playing. It could also function as muting music when game pages are open just because people want that to happen. I'd like it to unpause the music when the launch page of a game is closed.

**Comment by XxFran8234xX** [comment]
+1 For the "Game Theme Music" Plugin.

**Comment by WMan22** [comment]
Bonus points if it fades out the music volume before pausing it and fading it back in after unpausing it, so it feels more like an official feature meant all along to work in tandem with gameview. Kinda like how the Nintendo Wii used to do it. Would like the fade options on a toggle in case a certain track doesn't go well with a fade in and out.

**Comment by EMERALD0874** [comment]
Tested with Game Theme Music and this is resolved.
